### ISSUE TITLE
Could you please send me the paper?

### ISSUE THREAD

**Issue by wuzhen247** [erfan-ghadery/MNCN#1]
Dear Erfan,
      I come across your valuable paper "MNCN: A Multilingual Ngram-based Convolutional Network for Aspect Category Detection in Online Reviews" and am really interested in it. But I don't know where to read your paper. Could you please send me the paper? My email is wuzhen247@gmail.com. I really appreciate your help.

**Comment by erfan-ghadery** [comment]
> Dear Erfan,
> I come across your valuable paper "MNCN: A Multilingual Ngram-based Convolutional Network for Aspect Category Detection in Online Reviews" and am really interested in it. But I don't know where to read your paper. Could you please send me the paper? My email is [wuzhen247@gmail.com](mailto:wuzhen247@gmail.com). I really appreciate your help.

Thank you for your interest. The paper is not published yet but I will send the camera-ready version to your email.
